version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/masterdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JWT_SECRET=verysecretkeythatshouldbechangedinproduction1234567890
      - JWT_ACCESS_TOKEN_TTL=900000
      - JWT_REFRESH_TOKEN_TTL=1209600000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - micro_net

  # ======================
  # CORE DATABASE & MESSAGING
  # ======================
  postgres:
    image: postgres:16-alpine
    container_name: postgres_main
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masterdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 6s
      timeout: 5s
      retries: 5
    networks:
      - micro_net

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka_main
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - micro_net

  redis:
    image: redis:7.4-alpine
    container_name: redis_main
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 4s
      timeout: 3s
      retries: 5
    networks:
      - micro_net

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight_ui
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - micro_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
